INSERT INTO ANTMS.TBUSS007 (STA2, DSCA) VALUES (0, '低');
INSERT INTO ANTMS.TBUSS007 (STA2, DSCA) VALUES (1, '中');
INSERT INTO ANTMS.TBUSS007 (STA2, DSCA) VALUES (2, '高');
INSERT INTO ANTMS.TBUSS007 (STA2, DSCA) VALUES (3, '紧急');