INSERT INTO ANTMS.UTILL001 (STAT, DSCA) VALUES (0, '私有');
INSERT INTO ANTMS.UTILL001 (STAT, DSCA) VALUES (1, '组内');
INSERT INTO ANTMS.UTILL001 (STAT, DSCA) VALUES (2, '科室');
INSERT INTO ANTMS.UTILL001 (STAT, DSCA) VALUES (3, '部门');
INSERT INTO ANTMS.UTILL001 (STAT, DSCA) VALUES (4, '公司');
INSERT INTO ANTMS.UTILL001 (STAT, DSCA) VALUES (5, '完全公开');