INSERT INTO ANTMS.CBASE016 (CTYP, DSCA) VALUES ('1', '周报');
INSERT INTO ANTMS.CBASE016 (CTYP, DSCA) VALUES ('2', '智库');
INSERT INTO ANTMS.CBASE016 (CTYP, DSCA) VALUES ('3', '公开信息');
INSERT INTO ANTMS.CBASE016 (CTYP, DSCA) VALUES ('4', '学习文档');
INSERT INTO ANTMS.CBASE016 (CTYP, DSCA) VALUES ('5', '系统文档');